name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    #paths:
    #  - 'markdown/**.md'
      
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: markdown
          images_dir: images
          output_dir: pdfs
          # for example <img src="./images/file-name.png">
          #image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: true
      - uses: actions/upload-artifact@v2
        with:
          name: markdown
          path: pdfs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.6.1
        env:
            # The token is built in to actions. No config required.
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            COMMIT_MESSAGE: Add .pdf files.
            PULL_REQUEST_TITLE: Add .pdf files.
            PULL_REQUEST_BRANCH: pdf-add
            PULL_REQUEST_BODY: Here are the .pdf files you requested.
            PULL_REQUEST_REVIEWERS: pushou
